#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.
set -x
if [ -a ${OPENSHIFT_REPO_DIR}wr/server.xml ]
then
	cd ${OPENSHIFT_REPO_DIR}wr
	mv server.xml ${OPENSHIFT_DATA_DIR}tomcat/conf
fi
echo "starting tomcat"
echo "removing work directory"
rm -rf ${OPENSHIFT_DATA_DIR}/tomcat/work
echo "work directory removed"
cd ${OPENSHIFT_DATA_DIR}/tomcat
rsync -r --delete --exclude ".*" ${OPENSHIFT_REPO_DIR}/wr/webapps/ ${OPENSHIFT_DATA_DIR}/tomcat/webapps/
echo "webapps folder copied"